### ISSUE TITLE
Panic on `log` instrumentation

### ISSUE THREAD

**Issue by fermayo** [undefinedlabs/scope-go-agent#65]
```
panic: runtime error: slice bounds out of range [20:1]

goroutine 148 [running]:
go.undefinedlabs.com/scopeagent.loggerStdIOHandler(0xc000170360, 0xc000e8a080)
    /root/go/pkg/mod/go.undefinedlabs.com/scopeagent@v0.0.0-20190924185420-1636227ee401/testing.go:256 +0x768
created by go.undefinedlabs.com/scopeagent.startTestFromCaller
    /root/go/pkg/mod/go.undefinedlabs.com/scopeagent@v0.0.0-20190924185420-1636227ee401/testing.go:128 +0x701
```

**Comment by tonyredondo** [comment]
Do you have a working example for this bug? Because the slice thing is based in the internal logger format in go.  That way we can known why the timestamp is not being rendered causing the slice panic.

**Comment by tonyredondo** [comment]
Ok don’t worry I just saw the okteto recording. I think I know where is the problem. I’m parsing the logs line by line expecting the timestamp info of the logger. A panic could happen if a log entry has multiple lines \n because only the first line would have the timestamp info, causing the panic in the second line in the slice. So we should change the algorithm to try parse or ignore

**Comment by fermayo** [comment]
> Ok don’t worry I just saw the okteto recording. I think I know where is the problem. I’m parsing the logs line by line expecting the timestamp info of the logger. A panic could happen if a log entry has multiple lines \n because only the first line would have the timestamp info, causing the panic in the second line in the slice. So we should change the algorithm to try parse or ignore

Seems like we could add those extra lines to the one with the timestamp?

**Comment by fermayo** [comment]
Basically we have to take into account all the different possibilities that the standard logger provides: not only different configuration options for timestamp, but also the ability to add a prefix, and show the short/long file name and line number.

**Comment by tonyredondo** [comment]
> Basically we have to take into account all the different possibilities that the standard logger provides: not only different configuration options for timestamp, but also the ability to add a prefix, and show the short/long file name and line number.

Yeah we should, but the difficult part is we don't have access to the inner buffer neither possibility to intersect the logger, we are consuming the standard output line by line:

https://github.com/undefinedlabs/scope-go-agent/blob/1636227ee4018f1b192ef7c1c89af2e4a629d23c/testing.go#L239

So we have to guess about the prefix, about the timestamp and about the multiline entries.

About the timestamp the logger has some flags:
https://github.com/undefinedlabs/scope-go-agent/blob/1636227ee4018f1b192ef7c1c89af2e4a629d23c/testing.go#L244

that flags can give us information about the timestamp format as we see in go source code: 
https://github.com/golang/go/blob/57662b1575030aa09043cd7a48425abdc6e0e0a3/src/log/log.go#L37-L46

we even can get the prefix from: 
https://github.com/golang/go/blob/57662b1575030aa09043cd7a48425abdc6e0e0a3/src/log/log.go#L294-L297

the algorithm has to be basically a reverse of this method:
https://github.com/golang/go/blob/57662b1575030aa09043cd7a48425abdc6e0e0a3/src/log/log.go#L100-L150

The only thing to solve is the multiline logs, because the logger doesn't tell me when a log entry start and end, and I'm currently processing line by line with the `\n`

**Comment by fermayo** [comment]
> The only thing to solve is the multiline logs, because the logger doesn't tell me when a log entry start and end, and I'm currently processing line by line with the `\n`

If we parse the timestamp and add it to the event, maybe we can just hold a buffer and append to it if we parse lines without the expected prefix?

**Comment by tonyredondo** [comment]
> > The only thing to solve is the multiline logs, because the logger doesn't tell me when a log entry start and end, and I'm currently processing line by line with the `\n`
> 
> If we parse the timestamp and add it to the event, maybe we can just hold a buffer and append to it if we parse lines without the expected prefix?

Yeah, and flush the remaining data in the buffer if we reach the end of a test.

**Comment by fermayo** [comment]
> Yeah, and flush the remaining data in the buffer if we reach the end of a test.

We can flush the multi-line event in the buffer once we get a timestamp/prefix/filename, or we stop reading. We would only hold one event at a time.

**Comment by tonyredondo** [comment]
> > Yeah, and flush the remaining data in the buffer if we reach the end of a test.
> 
> We can flush the multi-line event in the buffer once we get a timestamp/prefix/filename, or we stop reading. We would only hold one event at a time.

Yes, sounds good to me.
